title: Shixuan Gu 顾诗轩
url: "https://ankitsultana.com"
baseurl: "/researcher"

markdown: kramdown
ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "CV_Shixuan_Gu.pdf"
 - name: "Contact"
   link: "contact"
